### ISSUE TITLE
个人专属报告：pyinstall的时候报错

### ISSUE THREAD

**Issue by CurtainRight** [shengqiangzhang/examples-of-web-crawlers#102]
3448 ERROR: base_library.zip could not be created!
Traceback (most recent call last):
  File "D:\obj\Windows-Release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\Windows-Release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "E:\work\install\python-3.7.2\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "e:\work\install\python-3.7.2\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "e:\work\install\python-3.7.2\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "e:\work\install\python-3.7.2\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "e:\work\install\python-3.7.2\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "E:\work\install\python-3.7.2\Scripts\test.spec", line 17, in <module>
    noarchive=False)
  File "e:\work\install\python-3.7.2\lib\site-packages\PyInstaller\building\build_main.py", line 243, in __init__
    self.__postinit__()
  File "e:\work\install\python-3.7.2\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "e:\work\install\python-3.7.2\lib\site-packages\PyInstaller\building\build_main.py", line 358, in assemble
    create_py3_base_library(libzip_filename, graph=self.graph)
  File "e:\work\install\python-3.7.2\lib\site-packages\PyInstaller\depend\utils.py", line 66, in create_py3_base_library
    st = os.stat(mod.filename)

**Comment by shengqiangzhang** [comment]
检查一下环境问题。
