### ISSUE TITLE
2.一键导出微信读书的书籍和笔记,脚本运行错误？

### ISSUE THREAD

**Issue by qwhhh** [shengqiangzhang/examples-of-web-crawlers#110]
装了最新的3.9版本，执行第一条就显示以下内容，请问怎么才能运行啊，谢谢。
D:\WX>pip uninstall -y -r requirement.txt
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\qwh\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\qwh\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\commands\uninstall.py", line 78, in run
    for parsed_req in parse_requirements(
  File "C:\Users\qwh\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\req\req_file.py", line 145, in parse_requirements
    for parsed_line in parser.parse(filename, constraint):
  File "C:\Users\qwh\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\req\req_file.py", line 326, in parse
    yield from self._parse_and_recurse(filename, constraint)
  File "C:\Users\qwh\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\req\req_file.py", line 331, in _parse_and_recurse
    for line in self._parse_file(filename, constraint):
  File "C:\Users\qwh\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\req\req_file.py", line 360, in _parse_file
    _, content = get_file_content(filename, self._session)
  File "C:\Users\qwh\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\req\req_file.py", line 533, in get_file_content
    content = auto_decode(f.read())
  File "C:\Users\qwh\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_internal\utils\encoding.py", line 34, in auto_decode
    return data.decode(
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 32447: illegal multibyte sequence

**Comment by panwanpeng** [comment]
Received. Many thanks!
I will read it quickly .
