### ISSUE TITLE
不知道报的啥错

### ISSUE THREAD

**Issue by safkdaskdfpokaspdofka** [shengqiangzhang/examples-of-web-crawlers#116]
Exception in thread generate_data:
Traceback (most recent call last):
  File "C:\Users\30550\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\30550\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "D:\workspace\课程设计\main.md.py", line 90, in generate_data
    detail_information = bot.get_detail_information()
  File "D:\workspace\课程设计\qq_bot.py", line 586, in get_detail_information
    g_tk = str(get_csrf_token(skey))
  File "D:\workspace\课程设计\decrypt.py", line 53, in get_csrf_token
    js = get_js('decrypt/getCSRFToken.js')
  File "D:\workspace\课程设计\decrypt.py", line 28, in get_js
    with open(js_name, 'r', encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'decrypt/getCSRFToken.js'

**Comment by panwanpeng** [comment]
Received. Many thanks!
I will read it quickly .
