### ISSUE TITLE
11.一键分析你的上网行为(web页面可视化)运行报错

### ISSUE THREAD

**Issue by Nq26rp** [shengqiangzhang/examples-of-web-crawlers#121]
楼主你好，我在运行该程序时遇到了以下报错问题，该如何解决呢
C:\Users\Eternal\Desktop\examples-of-web-crawlers-master\11.一键分析你的上网行为(web页面可视化)>python app.py
Traceback (most recent call last):
  File "C:\Users\Eternal\Desktop\examples-of-web-crawlers-master\11.一键分析你的上网行为(web页面可视化)\app.py", line 13, in <module>
    from app_configuration import app
  File "C:\Users\Eternal\Desktop\examples-of-web-crawlers-master\11.一键分析你的上网行为(web页面可视化)\app_configuration.py", line 21, in <module>
    app = dash.Dash(__name__)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Eternal\AppData\Local\Programs\Python\Python311\Lib\site-packages\dash\dash.py", line 338, in __init__
    self.init_app()
  File "C:\Users\Eternal\AppData\Local\Programs\Python\Python311\Lib\site-packages\dash\dash.py", line 377, in init_app
    self.server.before_first_request(self._setup_server)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Flask' object has no attribute 'before_first_request'. Did you mean: '_got_first_request'?

**Comment by Nq26rp** [comment]
@shengqiangzhang
