### ISSUE TITLE
运行不了程序

### ISSUE THREAD

**Issue by sunxing-1** [shengqiangzhang/examples-of-web-crawlers#19]
Getting uuid of QR code.
INFO:itchat:Getting uuid of QR code.
Downloading QR code.
INFO:itchat:Downloading QR code.
Traceback (most recent call last):
  File "generate_wx_data.py", line 542, in <module>
    bot = Bot(cache_path=True)
  File "E:\Program Files\python37\lib\site-packages\wxpy\api\bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "E:\Program Files\python37\lib\site-packages\itchat\components\register.py", line 30, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "E:\Program Files\python37\lib\site-packages\itchat\components\login.py", line 44, in login
    picDir=picDir, qrCallback=qrCallback)
  File "E:\Program Files\python37\lib\site-packages\itchat\components\login.py", line 117, in get_QR
    utils.print_qr(picDir)
  File "E:\Program Files\python37\lib\site-packages\itchat\utils.py", line 85, in print_qr
    os.startfile(fileDir)
OSError: [WinError -2147221003] 找不到应用程序: 'QR.png'

**Comment by shengqiangzhang** [comment]
没有应用程序能够打开qr.png，你看看当前目录下有生成这张图没
