### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by skillnull** [shengqiangzhang/examples-of-web-crawlers#35]
正在获取微信好友数据信息，请耐心等待……
微信好友数据信息获取完毕

正在分析你的群聊，请耐心等待……
Traceback (most recent call last):
  File "getUrl.py", line 532, in <module>
    group_common_in()
  File "getUrl.py", line 498, in group_common_in
    bar = Bar('共同所在群聊分析')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyecharts-1.2.1-py3.7.egg/pyecharts/charts/chart.py", line 143, in __init__
    super().__init__(init_opts=init_opts)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyecharts-1.2.1-py3.7.egg/pyecharts/charts/chart.py", line 15, in __init__
    super().__init__(init_opts=init_opts)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyecharts-1.2.1-py3.7.egg/pyecharts/charts/base.py", line 29, in __init__
    self.width = _opts.get("width")
AttributeError: 'str' object has no attribute 'get'

**Comment by zqf123** [comment]
我也是这个问题，解决了吗。。。。
