### ISSUE TITLE
可以正常登陆，爬取第一页数据，但是之后滑块部分就出错了 

### ISSUE THREAD

**Issue by Daoling** [shengqiangzhang/examples-of-web-crawlers#48]
**Log如下:**
包邮威德博威No.5羽毛球五号场馆训练比赛12只装耐打稳定室内高手   月成交68评价732旺旺在线   55.00   //detail.tmall.com/item.htm?id=13074420768&skuId=22276410079&areaId=310100&user_id=748152180&cat_id=50043727&is_b=1&rn=aa934dd095dab511c3ed3f2cde0da7b6

get button failed:  Message: move target out of bounds
  (Session info: chrome=76.0.3809.87)

Traceback (most recent call last):
  File "C:/Users/Daoling/Downloads/Tmall.py", line 216, in <module>
    a.crawl_good_data()  # 爬取天猫商品数据
  File "C:/Users/Daoling/Downloads/Tmall.py", line 150, in crawl_good_data
    EC.presence_of_element_located((By.CSS_SELECTOR, '#J_ItemList > div.product > div.product-iWrap')))
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

报错截图：

![微信图片_20190804114913](https://user-images.githubusercontent.com/5935711/62419275-e8ee3200-b6ae-11e9-88bf-5a69dbb8cb7b.png)

**Comment by Wiidz** [comment]
我是登录能登录，爬第一页的时候报错
```bash
tmall_crawler.py:128: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if(err1 == "喵~没找到"):
可以爬取这些信息
Traceback (most recent call last):
  File "tmall_crawler.py", line 214, in <module>
    a.crawl_good_data() #爬取天猫商品数据
  File "tmall_crawler.py", line 144, in crawl_good_data
    page_total = self.search_toal_page()
  File "tmall_crawler.py", line 84, in search_toal_page
    page_total = number_total.text.replace("共","").replace("页，到第页 确定","").replace("，","")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
```

**Comment by reborm** [comment]
这是被淘宝检测到使用selenium了，有大神能把这个破了么
