### ISSUE TITLE
出现如下问题

### ISSUE THREAD

**Issue by BarryBooder** [shengqiangzhang/examples-of-web-crawlers#57]
Exception in thread generate_data:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "main.py", line 152, in generate_data
TypeError: 'NoneType' object is not subscriptable

**Comment by shengqiangzhang** [comment]
@BarryBooder 

请具体说明是哪个文件以及你的python版本号。
