### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by mark988** [shengqiangzhang/examples-of-web-crawlers#67]
正在分析你的群聊，请耐心等待……
Traceback (most recent call last):
  File "generate_wx_data.py", line 564, in <module>
    group_common_in()
  File "generate_wx_data.py", line 527, in group_common_in
    bar = Bar('m1')
  File "/usr/local/lib/python3.7/site-packages/pyecharts/charts/chart.py", line 148, in __init__
    super().__init__(init_opts=init_opts)
  File "/usr/local/lib/python3.7/site-packages/pyecharts/charts/chart.py", line 14, in __init__
    super().__init__(init_opts=init_opts)
  File "/usr/local/lib/python3.7/site-packages/pyecharts/charts/base.py", line 28, in __init__
    self.width = _opts.get("width", "900px")
AttributeError: 'str' object has no attribute 'get'

**Comment by zhihuitang** [comment]
已修复：https://github.com/shengqiangzhang/examples-of-web-crawlers/pull/68

**Comment by shengqiangzhang** [comment]
已由 @zhihuitang 修复。
