### ISSUE TITLE
运行generate_wx_data.py时NameError: name 'Bot' is not defined

### ISSUE THREAD

**Issue by diaosilidsl** [shengqiangzhang/examples-of-web-crawlers#85]
Traceback (most recent call last):
  File "generate_wx_data.py", line 552, in <module>
    bot = Bot()
NameError: name 'Bot' is not defined

**Comment by shengqiangzhang** [comment]
@diaosilidsl 

没有安装wxpy，执行以下安装命令pip install -r requirement.txt

**Comment by diaosilidsl** [comment]
上述问题已解决，感谢！但是运行又出现了新问题
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 662, in urlopen
    self._prepare_proxy(conn)
  File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 948, in _prepare_proxy
    conn.connect()
  File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 308, in connect
    self._tunnel()
  File "D:\ProgramData\Anaconda3\lib\http\client.py", line 916, in _tunnel
    (version, code, message) = response._read_status()
  File "D:\ProgramData\Anaconda3\lib\http\client.py", line 288, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 662, in urlopen
    self._prepare_proxy(conn)
  File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 948, in _prepare_proxy
    conn.connect()
  File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 308, in connect
    self._tunnel()
  File "D:\ProgramData\Anaconda3\lib\http\client.py", line 916, in _tunnel
    (version, code, message) = response._read_status()
  File "D:\ProgramData\Anaconda3\lib\http\client.py", line 288, in _read_status
    raise BadStatusLine(line)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('\r\n'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\itchat\utils.py", line 124, in test_connect
    r = requests.get(config.BASE_URL)
  File "D:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('\r\n'))

You can't get access to internet or wechat domain, so exit.

**Comment by shengqiangzhang** [comment]
可能你的账号无法登录微信网页版，打开wx.qq.com手动扫码登录试试，如果登录不了，说明你的账号比较新，被微信官网禁止，微信官网已逐步关闭网页登录通道。





------------------ 原始邮件 ------------------
发件人: diaosilidsl <notifications@github.com&gt;
发送时间: 2020年4月18日 12:00
收件人: shengqiangzhang/examples-of-web-crawlers <examples-of-web-crawlers@noreply.github.com&gt;
抄送: Shengqiang Zhang <sqzhang77@gmail.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[shengqiangzhang/examples-of-web-crawlers] 运行generate_wx_data.py时NameError: name 'Bot' is not defined (#85)





 
上述问题已解决，感谢！但是运行又出现了新问题
 Traceback (most recent call last):
 File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 662, in urlopen
 self._prepare_proxy(conn)
 File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 948, in _prepare_proxy
 conn.connect()
 File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 308, in connect
 self._tunnel()
 File "D:\ProgramData\Anaconda3\lib\http\client.py", line 916, in _tunnel
 (version, code, message) = response._read_status()
 File "D:\ProgramData\Anaconda3\lib\http\client.py", line 288, in _read_status
 raise BadStatusLine(line)
 http.client.BadStatusLine:
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
 File "D:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 449, in send
 timeout=timeout
 File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
 method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
 File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 400, in increment
 raise six.reraise(type(error), error, _stacktrace)
 File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
 raise value.with_traceback(tb)
 File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 662, in urlopen
 self._prepare_proxy(conn)
 File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 948, in _prepare_proxy
 conn.connect()
 File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 308, in connect
 self._tunnel()
 File "D:\ProgramData\Anaconda3\lib\http\client.py", line 916, in _tunnel
 (version, code, message) = response._read_status()
 File "D:\ProgramData\Anaconda3\lib\http\client.py", line 288, in _read_status
 raise BadStatusLine(line)
 urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('\r\n'))
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
 File "D:\ProgramData\Anaconda3\lib\site-packages\itchat\utils.py", line 124, in test_connect
 r = requests.get(config.BASE_URL)
 File "D:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 76, in get
 return request('get', url, params=params, **kwargs)
 File "D:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 61, in request
 return session.request(method=method, url=url, **kwargs)
 File "D:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 530, in request
 resp = self.send(prep, **send_kwargs)
 File "D:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 643, in send
 r = adapter.send(request, **kwargs)
 File "D:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 498, in send
 raise ConnectionError(err, request=request)
 requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('\r\n'))
 
You can't get access to internet or wechat domain, so exit.

**Comment by diaosilidsl** [comment]
试了试，确实登不了，我账号应该还是算是老号吧......谢谢啦 @shengqiangzhang
