### ISSUE TITLE
不知为什么，明明下载了chromedrive,也修改了路径，还是报错

### ISSUE THREAD

**Issue by wxhzhwxhzh** [shengqiangzhang/examples-of-web-crawlers#88]
chromedriver.exe出错，请检查是否与你的chrome浏览器版本相匹配？？

**Comment by wxhzhwxhzh** [comment]
File "C:\Users\Administrator\Desktop\git\examples-of-web-crawlers\6.爬取豆瓣排行榜电影数据(含GUI界面版)\getMovieInRankingList.py", line 95, in get_url_data_in_keyWord
   self.browser.get('https://movie.douban.com/subject_search?search_text=' + urllib.parse.quote(
ttributeError: 'getMovieInRankingList' object has no attribute 'browser'

**Comment by shengqiangzhang** [comment]
```python
        try:
            self.browser = webdriver.Chrome(executable_path='/Users/bird/Desktop/chromedriver.exe',chrome_options=chrome_options)  # 设置chromedriver路径
            self.wait = WebDriverWait(self.browser, 10)  # 超时时长为10s
        except:
            print("chromedriver.exe出错，请检查是否与你的chrome浏览器版本相匹配\n缺失chromedriver.exe不会导致从排行榜搜索功能失效，但会导致从关键字搜索功能失效")
```

请列出以上代码段中你自己的代码

**Comment by wxhzhwxhzh** [comment]
try:
            self.browser = webdriver.Chrome(executable_path='D:/66/chromedriver.exe',chrome_options=chrome_options)  # 设置chromedriver路径
            self.wait = WebDriverWait(self.browser, 10)  # 超时时长为10s
        except:
            print("chromedriver.exe出错，请检查是否与你的chrome浏览器版本相匹配\n缺失chromedriver.exe不会导致从排行榜搜索功能失效，但会导致从关键字搜索功能失效")

**Comment by wxhzhwxhzh** [comment]
> ```python
>         try:
>             self.browser = webdriver.Chrome(executable_path='/Users/bird/Desktop/chromedriver.exe',chrome_options=chrome_options)  # 设置chromedriver路径
>             self.wait = WebDriverWait(self.browser, 10)  # 超时时长为10s
>         except:
>             print("chromedriver.exe出错，请检查是否与你的chrome浏览器版本相匹配\n缺失chromedriver.exe不会导致从排行榜搜索功能失效，但会导致从关键字搜索功能失效")
> ```
> 
> 请列出以上代码段中你自己的代码

        try:
            self.browser = webdriver.Chrome(executable_path='D:/66/chromedriver.exe',chrome_options=chrome_options)  # 设置chromedriver路径
            self.wait = WebDriverWait(self.browser, 10)  # 超时时长为10s
        except:
            print("chromedriver.exe出错，请检查是否与你的chrome浏览器版本相匹配\n缺失chromedriver.exe不会导致从排行榜搜索功能失效，但会导致从关键字搜索功能失效")

**Comment by wxhzhwxhzh** [comment]
下面的是另一报错：

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\git\examples-of-web-crawlers\6.爬取豆瓣排行榜电影数据(含GUI界面版)\uiObject.py", line 448, in searh_movie_in_keyword
    list,jsonData = movieObject.get_url_data_in_keyWord(self.T_vote_keyword.get())
  File "C:\Users\Administrator\Desktop\git\examples-of-web-crawlers\6.爬取豆瓣排行榜电影数据(含GUI界面版)\getMovieInRankingList.py", line 95, in get_url_data_in_keyWord
    self.browser.get('https://movie.douban.com/subject_search?search_text=' + urllib.parse.quote(
AttributeError: 'getMovieInRankingList' object has no attribute 'browser'

**Comment by shengqiangzhang** [comment]
请以截图形式发送，截你运行代码的命令，以及完整的错误截图。





------------------ 原始邮件 ------------------
发件人: wxhzhwxhzh <notifications@github.com&gt;
发送时间: 2020年4月23日 15:47
收件人: shengqiangzhang/examples-of-web-crawlers <examples-of-web-crawlers@noreply.github.com&gt;
抄送: Shengqiang Zhang <sqzhang77@gmail.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[shengqiangzhang/examples-of-web-crawlers] 不知为什么，明明下载了chromedrive,也修改了路径，还是报错 (#88)





 
下面的是另一报错：
 
Exception in thread Thread-2:
 Traceback (most recent call last):
 File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
 self.run()
 File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
 self._target(*self._args, **self._kwargs)
 File "C:\Users\Administrator\Desktop\git\examples-of-web-crawlers\6.爬取豆瓣排行榜电影数据(含GUI界面版)\uiObject.py", line 448, in searh_movie_in_keyword
 list,jsonData = movieObject.get_url_data_in_keyWord(self.T_vote_keyword.get())
 File "C:\Users\Administrator\Desktop\git\examples-of-web-crawlers\6.爬取豆瓣排行榜电影数据(含GUI界面版)\getMovieInRankingList.py", line 95, in get_url_data_in_keyWord
 self.browser.get('https://movie.douban.com/subject_search?search_text=' + urllib.parse.quote(
 AttributeError: 'getMovieInRankingList' object has no attribute 'browser'

**Comment by wxhzhwxhzh** [comment]
![360截图20200424121915561](https://user-images.githubusercontent.com/21326329/80174953-d514a280-8626-11ea-95e4-648f69a9575b.jpg)
如图所示

**Comment by shengqiangzhang** [comment]
版本不匹配，你可能下载错了







------------------ 原始邮件 ------------------
发件人: wxhzhwxhzh <notifications@github.com&gt;
发送时间: 2020年4月24日 12:27
收件人: shengqiangzhang/examples-of-web-crawlers <examples-of-web-crawlers@noreply.github.com&gt;
抄送: Shengqiang Zhang <sqzhang77@gmail.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[shengqiangzhang/examples-of-web-crawlers] 不知为什么，明明下载了chromedrive,也修改了路径，还是报错 (#88)





 

 如图所示
