### ISSUE TITLE
2.天猫商品数据爬虫(已模拟登录)  报错

### ISSUE THREAD

**Issue by lh2199** [shengqiangzhang/examples-of-web-crawlers#96]
C:\Users\Administrator\Downloads\examples-of-web-crawlers\2.天猫商品数据爬虫(已模拟登录)>tmall_crawler.py

DevTools listening on ws://127.0.0.1:57658/devtools/browser/ce173f91-456f-46c5-b389-189dd26c187f
[21908:20924:0630/184159.033:ERROR:device_event_log_impl.cc(208)] [18:41:59.033] Bluetooth: bluetooth_adapter_winrt.cc:1150 RequestRadioAccessAsync failed: RadioAccessStatus::DeniedByUserWill not be able to change radio power.
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\examples-of-web-crawlers\2.天猫商品数据爬虫(已模拟登录)\tmall_crawler.py", line 216, in <module>
    a.login() #登录
  File "C:\Users\Administrator\Downloads\examples-of-web-crawlers\2.天猫商品数据爬虫(已模拟登录)\tmall_crawler.py", line 50, in login
    self.browser.find_element_by_xpath('//*[@class="forget-pwd J_Quick2Static"]').click()
  File "D:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "D:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "D:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@class="forget-pwd J_Quick2Static"]"}
  (Session info: chrome=83.0.4103.116)

python3.8.2   win10 x64企业版

**Comment by Hyper-wyu** [comment]
Same bro.
