### ISSUE TITLE
QQ报错

### ISSUE THREAD

**Issue by lei940324** [shengqiangzhang/examples-of-web-crawlers#98]
获取不到好友信息

以下为报错信息：
```
Exception in thread generate_data:
Traceback (most recent call last):
  File "C:\software\anaconda\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\software\anaconda\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 148, in generate_data
    all_qq_friends = bot.get_all_friends_in_qq()
  File "C:\Users\54722\Desktop\examples-of-web-crawlers\9.一键生成QQ个人历史报告
\qq_bot.py", line 336, in get_all_friends_in_qq
    return friend_info['result']
KeyError: 'result'
```

**Comment by shengqiangzhang** [comment]
经过测试，发现没有问题。可能是频繁登录了，建议过段时间登录。

**Comment by shengqiangzhang** [comment]
@lei940324 已修复，详见[https://github.com/shengqiangzhang/examples-of-web-crawlers/commit/97f3342fb5bf018b515f5049730c04c54c2bb717](https://github.com/shengqiangzhang/examples-of-web-crawlers/commit/97f3342fb5bf018b515f5049730c04c54c2bb717)

**Comment by panwanpeng** [comment]
Received. Many thanks!
I will read it quickly .

**Comment by safkdaskdfpokaspdofka** [comment]
不知道啥错
Exception in thread generate_data:
Traceback (most recent call last):
  File "C:\Users\30550\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\30550\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "D:\workspace\课程设计\main.md.py", line 90, in generate_data
    detail_information = bot.get_detail_information()
  File "D:\workspace\课程设计\qq_bot.py", line 586, in get_detail_information
    g_tk = str(get_csrf_token(skey))
  File "D:\workspace\课程设计\decrypt.py", line 53, in get_csrf_token
    js = get_js('decrypt/getCSRFToken.js')
  File "D:\workspace\课程设计\decrypt.py", line 28, in get_js
    with open(js_name, 'r', encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'decrypt/getCSRFToken.js'
